version: '3'

services:
    dev-vault:
        image: vault
        ports:
            - 8200:8200
        volumes:
            - ./volumes/file:/vault/file
            - ./volumes/config:/vault/config
            - ./volumes/tls:/vault/tls
        environment:
            - VAULT_LOG_LEVEL=info
            - VAULT_ADDR=https://127.0.0.1:8200
            - VAULT_API_ADDR=https://127.0.0.1:8200
        cap_add:
            - IPC_LOCK
        command: server
